### ISSUE TITLE
Having trouble making after opencv upgrade

### ISSUE THREAD

**Issue by eeeps** [cloudinary/ssimulacra#6]
Trying to build ssimulacra on OS X 14.2 and running into an issue.

```
$ make
g++ -std=c++11 -O2 -fstrict-aliasing -ffast-math `pkg-config --cflags opencv` ssimulacra.cpp `pkg-config --libs-only-L opencv` -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -o ssimulacra
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
ssimulacra.cpp:81:10: fatal error: 'cv.hpp' file not found
#include <cv.hpp>
         ^~~~~~~~
1 error generated.
make: *** [ssimulacra] Error 1
```

I’m assuming this is related to the fact that Homebrew recently upgraded my opencv to version 4.

I took a stab at fixing it by finding the closest thing I could to `opencv.pc` and symlinking it to that path:

```
ln -s /usr/local/Cellar/opencv/4.0.1/lib/pkgconfig/opencv4.pc /usr/local/lib/pkgconfig/opencv.pc
```

And while that got rid of the first error, I still ran into the `'cv.hpp' file not found` error.

Any advice?

**Comment by tpiros** [comment]
@eeeps - change the source to the following in ssimulacra.cpp:

```
#include <opencv2/opencv.hpp>
#include <stdio.h>
#include <set>
```

If you're using OpenCV3+ (which, based on your comments seem to be the case) there's no need to add `highgui` either, so the above should suffice. Hope this helps.

**Comment by malchata** [comment]
I saw that you referenced this issue in #7, @tpiros, and I appreciate the note. :)

Is it doable to move this into the source so that it's a part of the repo, or are there problems with this? I currently have [a project](https://github.com/malchata/ssimulacra-bin] that may have issues with OpenCV dependencies, and my only other option would be to include a copy of the source with this modification, rather than fetch the .cpp from Github directly like I do now.
